In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [6]:
# axis=0(竖直轴)表示python在竖直方向求和；axis=1（水平轴）表示python在水平方向求和
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [4]:
percentage = 100*A/cal.reshape(1, 4)   # np.reshape(1,4)指令经常使用，复杂度o(1)
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [7]:
a = np.array([1, 2, 3, 4])
b = 100
a = a.reshape((4, 1))
c = a + b
print(c)

[[101]
 [102]
 [103]
 [104]]


In [8]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([100, 200, 300])
C = A + B
print(C)

[[101 202 303]
 [104 205 306]]


In [11]:
D = np.array([[100], [200]])
print(D.shape)
E = A + D
print(E)

(2, 1)
[[101 102 103]
 [204 205 206]]


In [13]:
"广播中的通用规则"

"""
(m,n)  + - * / (1,n)时，（1，n）首先先复制成为(m,n),之后再进行运算
(m,n)  + - * / (m,1)时，（m，1）首先先复制成为(m,n),之后再进行运算
(m,1)  + 一个实数时，首先先把这个实数先复制m次，得到另一个(m,1)的矩阵，然后执行运算
"""

import requests
import urllib


url = "https://www.baidu.com"
req = requests.get(url)
req.encoding = 'utf-8'
print(req.text)




<!DOCTYPE html>
<!--STATUS OK--><html> <head><meta http-equiv=content-type content=text/html;charset=utf-8><meta http-equiv=X-UA-Compatible content=IE=Edge><meta content=always name=referrer><link rel=stylesheet type=text/css href=https://ss1.bdstatic.com/5eN1bjq8AAUYm2zgoY3K/r/www/cache/bdorz/baidu.min.css><title>百度一下，你就知道</title></head> <body link=#0000cc> <div id=wrapper> <div id=head> <div class=head_wrapper> <div class=s_form> <div class=s_form_wrapper> <div id=lg> <img hidefocus=true src=//www.baidu.com/img/bd_logo1.png width=270 height=129> </div> <form id=form name=f action=//www.baidu.com/s class=fm> <input type=hidden name=bdorz_come value=1> <input type=hidden name=ie value=utf-8> <input type=hidden name=f value=8> <input type=hidden name=rsv_bp value=1> <input type=hidden name=rsv_idx value=1> <input type=hidden name=tn value=baidu><span class="bg s_ipt_wr"><input id=kw name=wd class=s_ipt value maxlength=255 autocomplete=off autofocus=autofocus></span><span class="bg s_btn