In [1]:
import numpy as np


a = np.random.randn(5)  # 生成5个随机高斯变量,称为秩为1的数组
print(a)


[ 1.75834312 -0.6656999  -0.23609892 -0.97755393  1.8638894 ]


In [2]:
print(a.shape)  # (5,)秩为1的数组，并不是行向量或者列向量

(5,)


In [3]:
print(a.T) # 秩为1的数组，尽量不要用此结构

[ 1.75834312 -0.6656999  -0.23609892 -0.97755393  1.8638894 ]


In [4]:
print(np.dot(a, a.T))

8.02036495824


In [5]:
a = np.random.randn(5,1)
print(a)

[[ 0.26657432]
 [ 1.08751487]
 [-0.25720538]
 [ 0.01558244]
 [ 0.13759452]]


In [6]:
print(a.T) # 表示1*5的矩阵

[[ 0.26657432  1.08751487 -0.25720538  0.01558244  0.13759452]]


In [7]:
print(np.dot(a, a.T))

[[  7.10618671e-02   2.89903535e-01  -6.85643496e-02   4.15387812e-03
    3.66791663e-02]
 [  2.89903535e-01   1.18268859e+00  -2.79714679e-01   1.69461344e-02
    1.49636090e-01]
 [ -6.85643496e-02  -2.79714679e-01   6.61546091e-02  -4.00788726e-03
   -3.53900521e-02]
 [  4.15387812e-03   1.69461344e-02  -4.00788726e-03   2.42812413e-04
    2.14405830e-03]
 [  3.66791663e-02   1.49636090e-01  -3.53900521e-02   2.14405830e-03
    1.89322529e-02]]


In [19]:
a = np.array([[1, 2, 3, 4]])  # 推荐使用这种
b = np.array([1, 2, 3, 4])   # 不推荐使用秩为1的数组
print(a.shape)
print(b.shape)
b = b.reshape(1, 4)   # 利用reshape指令将一个秩为1的数组转成列向量
print(b)

(1, 4)
(4,)
[[1 2 3 4]]


In [15]:
a = np.random.randn(5, 1)
print(a.shape)
b = np.random.randn(1, 5)
print(b.shape)
print(a)
print(b)
# 不太确定一个向量具体的维度是多少时，加入assert()语句，确保向量的维度是正确的
assert(a.shape == (5, 1))

(5, 1)
(1, 5)
[[ 0.20088278]
 [-0.76203097]
 [ 0.08725335]
 [ 0.3423664 ]
 [ 0.65241721]]
[[ 0.5275791  -0.21490836  1.23677115 -0.4324681  -0.67690418]]
